# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://monitoria-qof-unb.github.io/"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Name of website
title: Química Orgânica Fundamental

#For my changes
# use meta-title: for the center heading of the page.
# use title: to set the <title> of the web page.
# use subtitle: to set the sub heading for that title(meta-title). NOTE: if(meta-title exists){subtilel visiblity = true}

# Short description of your site
description: Hey, bora aprender

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  # Uns livro ai: "livros"
  Sobre os monitores: "aboutme"
  # Aqui fica uma lista:
  #   - A framework of smart homes connected devices using Internet of Things: "http://ieeexplore.ieee.org/document/7918794/"
  #   - Google Scholar Profile: "https://scholar.google.co.in/citations?user=4p4smu0AAAAJ"
  #   - ResearchGate Profile: "https://www.researchgate.net/profile/Anudit_Verma"
  # Aqui é outra lista:
  #   - GSoC'15: "https://github.com/anuditverma/org.civicrm.osdi"
  #   - Airtel Suvidha (Airtel WHack Hackathon): "https://www.linkedin.com/feed/update/activity:6273369896978087936/"
  #   - Contract Reader Tool (EY Hackathon): "https://www.rlcf.ey.com/in/en/newsroom/news-releases/news-ey-annouces-winners-of-the-intelligent-automation-hackathon"
  #   - Medical Ambience App: "https://github.com/anuditverma/MAA-Avaya-Hackathon"
  #   - TypeRacer: "https://github.com/anuditverma/appbase-typeracer"
  #   - video.js Overlay Hyperlink: "https://www.npmjs.com/package/videojs-overlay-hyperlink"
  # Resume: "resume/Anudit_Verma.pdf"
  Tags: "tags"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/av.jpg"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter. The logo will have a height of 40px
# title-img: /path/to/image

# --- Background colour/image options --- #

# By default, the navigation bar and footer have a light gray background, and the main page
# has a white background. You can specify a different background colour or a background image
# for the navigation bar, the main page, and the footer.
# navbar-col: "#002b36"
# navbar-img: "/img/bgimage.png"
# footer-col: "#002b36"
# footer-img: "/img/bgimage.png"
# page-col: "#839496"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Feito com amor, seus monitores. S2
  email: "mcardosos99@gmail.com"
  # facebook: anuditverma
  github: Cardosaum
  twitter: _cardosaum_
  # google-plus: +AnuditVerma
  linkedin: matheus-c-souza
  stackoverflow: 10719703/evem-mc
  instagram: cardosaum
  reddit: Evem_MC
# xing: yourname
# stackoverflow: yourlink  # eg. "3943160/daattali"
# snapchat: yourname
# youtube: yourlink   # eg. user/daattali or channel/daattali
  spotify: cardosaum
# steam: yourname
# twitch: yourname
# yelp: yourname

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: false
  twitter: false
  google-plus: false
  github: false
  linkedin: false
  stackoverflow: false
  instagram: false
  reddit: false
  xing: false
  stackoverflow: false
  snapchat: false
  youtube: false
  spotify: false
  steam: false
  twitch: false
  yelp: false

# Select which share links to show in posts
share-links-active:
  twitter: false
  facebook: false
  google: false
  linkedin: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "www.monitoria-qof-unb.github.io"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
# disqus: "cardosaum"

# Fill in your Google Analytics ID to track your website using GA
# google_analytics: "UA-143011649-1"

# Google Tag Manager ID
#gtm: ""

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Brasilia"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: false # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

#Meta data for your Posts
metadata:
  _posts:
    - name: "layout"
      field:
        element: "hidden"
        value: "post"
    - name: "title"
      field:
        element: "text"
        label: "Post title"
        placeholder: "Title"
        alterable: true
    - name: "subtitle"
      field:
        element: "textarea"
        label: "Subtitle"
        placeholder: "A description of your post."
        alterable: true
    - name: "date"
      field:
        element: "text"
        label: "Date"
        help: "Enter date of post."
        placeholder: "yyyy-mm-dd"
        alterable: true
    - name: "image"
      field:
        element: "text"
        label: "Image"
        help: "Add a thumbnail image to your post."
        placeholder: "Thumbnail"
        alterable: true
    - name: "published"
      field:
        element: "checkbox"
        label: "Publish"
        help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap
